winget install Google.Drive
winget install DominikReichl.KeePass
winget install Joplin.Joplin
winget install Microsoft.VisualStudioCode
winget install Git.Git
winget install SublimeHQ.SublimeMerge
winget install SublimeHQ.SublimeText.3
winget install Oracle.VirtualBox
winget install Hashicorp.Vagrant
winget install ChefSoftware.Workstation
winget install ShareX.ShareX
winget install PuTTY.PuTTY
winget install WinSCP.WinSCP
winget install Whatsapp.Whatsapp
winget install VideoLAN.VLC
winget install WinDirStat.WinDirStat
winget install Python.Python.3
winget install Amazon.AWSCLI
winget install kubectl
